// PreToolUse (Edit|Write|MultiEdit): protect files that must not be hand-edited and scan new content for secrets.
// Bảo vệ file không được sửa tay (.env, lockfile, file sinh tự động...) và quét bí mật trong nội dung sắp ghi.
import fs from 'node:fs';
import path from 'node:path';
import { readInput, block, ask, t, config, disabled, absPath, relPath, isTestFile, findSecrets } from './lib.mjs';

const input = readInput();
const ti = input.tool_input || {};
const target = ti.file_path;
if (!target) process.exit(0);

const abs = absPath(target);
const rel = relPath(abs);
const base = path.basename(abs);
const cfg = config();
if (cfg.allowPaths.some((p) => new RegExp(p).test(rel))) process.exit(0);

// New content that is about to be written
const newContent = [ti.content, ti.new_string, ...(Array.isArray(ti.edits) ? ti.edits.map((e) => e.new_string) : [])]
  .filter((x) => typeof x === 'string')
  .join('\n');

const exists = fs.existsSync(abs);
let head = '';
if (exists) {
  try {
    head = fs.readFileSync(abs, 'utf8').slice(0, 800);
  } catch {
    /* binary or unreadable */
  }
}

const B = (id, m) => !disabled(id) && block(`Blocked [${id}] ${rel}: ${t(m)}`);

// ---------- DENY ----------
if (/^\.env(\..+)?$/.test(base) && !/\.(example|sample|template)$/.test(base))
  B('env-file', {
    en: 'Real .env files hold secrets and must never be edited by the agent. Put variable NAMES with safe dummy values in .env.example and tell the user what to set locally.',
    vi: 'File .env thật chứa bí mật, agent không được sửa. Hãy ghi TÊN biến kèm giá trị giả an toàn vào .env.example và nhắn người dùng tự điền ở máy mình.',
  });
if (/\.(pem|key|p12|pfx|jks|keystore)$/i.test(base) || /^id_(rsa|ed25519)(\.pub)?$/.test(base) || /(^|\/)\.aws\/credentials$/.test(rel))
  B('key-file', { en: 'Key/certificate/credential files must not be created or edited by the agent.', vi: 'Agent không được tạo/sửa file khoá, chứng chỉ, thông tin xác thực.' });
if (/(^|\/)(node_modules|\.git|\.next|dist|coverage|__pycache__|\.venv|venv|\.turbo|\.pytest_cache|\.mypy_cache|\.ruff_cache)\//.test(rel))
  B('build-output', { en: 'Build output, dependency, cache or VCS directory. Change the source instead.', vi: 'Đây là thư mục build, thư viện, cache hoặc VCS. Hãy sửa mã nguồn thay vì sửa ở đây.' });
if (/^(package-lock\.json|pnpm-lock\.yaml|yarn\.lock|bun\.lockb?|uv\.lock|poetry\.lock|Pipfile\.lock|composer\.lock)$/.test(base))
  B('lockfile', { en: 'Lockfiles are generated by the package manager. Run the install/lock command (after approval) instead of editing by hand.', vi: 'Lockfile do trình quản lý gói sinh ra. Hãy chạy lệnh cài/lock (sau khi được duyệt) thay vì sửa tay.' });
if (/(^|\/)(generated|__generated__)\//.test(rel) || /\.generated\.\w+$/.test(base) || /\.min\.(js|css)$/.test(base) || /@generated|DO NOT EDIT/i.test(head))
  B('generated-file', { en: 'Generated file. Edit the generator/source (OpenAPI, schema, template) and regenerate.', vi: 'File được sinh tự động. Hãy sửa nguồn sinh (OpenAPI, schema, template) rồi sinh lại.' });
if (cfg.extraProtectedPaths.some((p) => new RegExp(p).test(rel)))
  B('protected-path', { en: 'Path protected by .claude/hooks/config.json.', vi: 'Đường dẫn được bảo vệ bởi .claude/hooks/config.json.' });

// ---------- secrets in new content ----------
if (!disabled('secrets') && newContent && !/\.(example|sample|template)$/.test(base)) {
  const found = findSecrets(newContent, { relaxed: isTestFile(rel) });
  if (found.length) {
    const names = [...new Set(found.map((f) => f.name))].join(', ');
    block(
      `Blocked [secrets] ${rel}: ${t({
        en: `content looks like it contains a secret (${names}). Read it from configuration/environment instead of hard-coding it. Add "hook-ignore" on the line only if it is a harmless fixture.`,
        vi: `nội dung có vẻ chứa bí mật (${names}). Hãy đọc từ cấu hình/biến môi trường thay vì ghi cứng. Chỉ thêm "hook-ignore" trên dòng đó nếu là dữ liệu giả vô hại.`,
      })}`,
    );
  }
}

// ---------- ASK ----------
const A = (id, m) => !disabled(id) && ask(`[${id}] ${rel}: ${t(m)}`);

if (/^\.claude\/(settings(\.local)?\.json|hooks\/)/.test(rel))
  A('guardrail-edit', { en: 'This changes the project guardrails (hooks/settings).', vi: 'Thay đổi này sửa các rào chắn của dự án (hook/settings).' });
if (/^\.github\/workflows\//.test(rel) || /(^|\/)(\.gitlab-ci\.yml|Dockerfile[^/]*|docker-compose[^/]*\.ya?ml|Jenkinsfile)$/.test(rel) || /(^|\/)(terraform|k8s|kubernetes|helm|infra)\//.test(rel))
  A('ci-infra', { en: 'CI/CD, container or infrastructure change. Confirm before editing.', vi: 'Thay đổi CI/CD, container hoặc hạ tầng. Hãy xác nhận trước khi sửa.' });
if (exists && /(^|\/)migrations?\//.test(rel))
  A('existing-migration', { en: 'Editing an existing migration. Applied migrations must not change; add a new one instead.', vi: 'Đang sửa migration có sẵn. Migration đã áp dụng không được đổi; hãy tạo migration mới.' });
if (/(^|\/)(package\.json|pyproject\.toml|requirements[^/]*\.txt|Pipfile)$/.test(base)) {
  const depLike = /"[@\w./-]+"\s*:\s*"[~^<>=]*\d+\.\d+|^\s*[\w.-]+\s*(==|>=|~=)\s*\d|dependencies|^\s*"[\w.-]+\s*(==|>=|~=|<)/m.test(newContent);
  if (depLike) A('dependency-manifest', { en: 'This edit appears to add or change dependencies. Confirm (size, licence, security).', vi: 'Thay đổi này có vẻ thêm/đổi thư viện phụ thuộc. Hãy xác nhận (dung lượng, giấy phép, bảo mật).' });
}
